const posts = [
	{
		titulo: 'Cómo mejorar el rendimiento de tu sitio web con técnicas de optimización avanzadas',
		descripcion:
			'Descubre algunas técnicas avanzadas para mejorar el rendimiento de tu sitio web, desde la optimización del lado del servidor hasta la gestión eficiente de recursos en el cliente.',
		categoria: 'Desarrollo Web',
		autor: 'John Doe',
		tags: ['optimización', 'rendimiento', 'desarrollo web'],
		tiempoLectura: '10 minutos',
		fechaCreacion: '2024-04-25',
		imagen: 'https://picsum.photos/id/32/200/300',
		numReacciones: 56,
	},
	{
		titulo: 'Introducción a React Hooks: Cómo utilizar useState y useEffect',
		descripcion:
			'Aprende los conceptos básicos de React Hooks y cómo utilizar useState y useEffect para gestionar el estado y los efectos en tus aplicaciones React.',
		categoria: 'React',
		autor: 'Jane Smith',
		tags: ['React', 'Hooks', 'useState', 'useEffect'],
		tiempoLectura: '8 minutos',
		fechaCreacion: '2024-04-20',
		imagen: 'https://picsum.photos/id/33/200/300',
		numReacciones: 42,
	},
	{
		titulo: 'Guía completa de CSS Grid: Cómo crear diseños modernos y flexibles',
		descripcion:
			'Domina CSS Grid con esta guía completa que te enseñará a crear diseños modernos y flexibles para tus proyectos web.',
		categoria: 'CSS',
		autor: 'Juan Pérez',
		tags: ['CSS', 'CSS Grid', 'diseño web'],
		tiempoLectura: '12 minutos',
		fechaCreacion: '2024-04-18',
		imagen: 'https://picsum.photos/id/34/200/300',
		numReacciones: 73,
	},
	{
		titulo: '10 Consejos para escribir código limpio y mantenible',
		descripcion:
			'Descubre algunos consejos prácticos para escribir código limpio y mantenible que mejore la calidad y la legibilidad de tus proyectos de desarrollo.',
		categoria: 'Desarrollo Web',
		autor: 'Ana García',
		tags: ['código limpio', 'mantenibilidad', 'buenas prácticas'],
		tiempoLectura: '6 minutos',
		fechaCreacion: '2024-04-15',
		imagen: 'https://picsum.photos/id/35/200/300',
		numReacciones: 29,
	},
	{
		titulo: 'Cómo implementar autenticación de usuarios con Firebase en tu aplicación web',
		descripcion:
			'Aprende a utilizar Firebase Authentication para agregar fácilmente autenticación de usuarios a tu aplicación web y proteger tu contenido.',
		categoria: 'Firebase',
		autor: 'David López',
		tags: ['Firebase', 'autenticación', 'seguridad'],
		tiempoLectura: '9 minutos',
		fechaCreacion: '2024-04-12',
		imagen: 'https://picsum.photos/id/36/200/300',
		numReacciones: 38,
	},
	{
		titulo: 'Principios básicos de SEO para desarrolladores web',
		descripcion:
			'Conoce los principios básicos de SEO que todo desarrollador web debería entender para mejorar el posicionamiento y visibilidad de sus proyectos en buscadores.',
		categoria: 'SEO',
		autor: 'María Fernández',
		tags: [
			'SEO',
			'optimización para motores de búsqueda',
			'desarrollo web',
		],
		tiempoLectura: '7 minutos',
		fechaCreacion: '2024-04-10',
		imagen: 'https://picsum.photos/id/37/200/300',
		numReacciones: 51,
	},
	{
		titulo: 'Introducción a TypeScript: Principales características y ventajas',
		descripcion:
			'Descubre las principales características y ventajas de TypeScript y aprende cómo puede mejorar la calidad y mantenibilidad de tus proyectos JavaScript.',
		categoria: 'TypeScript',
		autor: 'Pedro Martínez',
		tags: ['TypeScript', 'JavaScript', 'tipado estático'],
		tiempoLectura: '11 minutos',
		fechaCreacion: '2024-04-05',
		imagen: 'https://picsum.photos/id/38/200/300',
		numReacciones: 62,
	},
	{
		titulo: 'Cómo mejorar la seguridad de tu aplicación web con medidas proactivas',
		descripcion:
			'Aprende a identificar y aplicar medidas proactivas para mejorar la seguridad de tu aplicación web y protegerla contra posibles vulnerabilidades.',
		categoria: 'Seguridad Web',
		autor: 'Elena Ruiz',
		tags: ['seguridad web', 'ciberseguridad', 'protección'],
		tiempoLectura: '9 minutos',
		fechaCreacion: '2024-04-02',
		imagen: 'https://picsum.photos/id/39/200/300',
		numReacciones: 45,
	},
	{
		titulo: '10 Herramientas útiles para el desarrollo web en 2024',
		descripcion:
			'Descubre algunas herramientas útiles que te ayudarán a mejorar tu flujo de trabajo y productividad como desarrollador web en el año 2024.',
		categoria: 'Herramientas',
		autor: 'Carlos González',
		tags: ['herramientas', 'desarrollo web', 'productividad'],
		tiempoLectura: '5 minutos',
		fechaCreacion: '2024-03-28',
		imagen: 'https://picsum.photos/id/40/200/300',
		numReacciones: 34,
	},
	{
		titulo: 'Cómo diseñar una API RESTful: Principios y buenas prácticas',
		descripcion:
			'Aprende los principios fundamentales y las mejores prácticas para diseñar una API RESTful que sea escalable, flexible y fácil de mantener.',
		categoria: 'APIs',
		autor: 'Laura Díaz',
		tags: ['APIs', 'REST', 'diseño de APIs'],
		tiempoLectura: '13 minutos',
		fechaCreacion: '2024-03-25',
		imagen: 'https://picsum.photos/id/41/200/300',
		numReacciones: 58,
	},
	{
		titulo: 'Guía completa de Bootstrap 5: Cómo crear sitios web modernos y responsivos',
		descripcion:
			'Aprende a utilizar Bootstrap 5 para crear sitios web modernos, responsivos y estéticamente atractivos con facilidad, gracias a su sistema de grid y componentes.',
		categoria: 'Bootstrap',
		autor: 'Pablo Rodríguez',
		tags: ['Bootstrap', 'diseño web', 'front-end'],
		tiempoLectura: '10 minutos',
		fechaCreacion: '2024-03-22',
		imagen: 'https://picsum.photos/id/42/200/300',
		numReacciones: 49,
	},
	{
		titulo: 'Introducción a GraphQL: Una alternativa moderna para el desarrollo de APIs',
		descripcion:
			'Descubre qué es GraphQL y cómo puede revolucionar la forma en que desarrollas APIs, ofreciendo flexibilidad y eficiencia en la transferencia de datos.',
		categoria: 'GraphQL',
		autor: 'Sara Navarro',
		tags: ['GraphQL', 'APIs', 'consulta de datos'],
		tiempoLectura: '8 minutos',
		fechaCreacion: '2024-03-20',
		imagen: 'https://picsum.photos/id/43/200/300',
		numReacciones: 37,
	},
	{
		titulo: 'Estrategias para mejorar la accesibilidad en tus proyectos web',
		descripcion:
			'Aprende estrategias prácticas para mejorar la accesibilidad de tus proyectos web y hacer que sean más inclusivos para todos los usuarios.',
		categoria: 'Accesibilidad',
		autor: 'Luisa Torres',
		tags: ['accesibilidad', 'usabilidad', 'diseño web'],
		tiempoLectura: '7 minutos',
		fechaCreacion: '2024-03-18',
		imagen: 'https://picsum.photos/id/44/200/300',
		numReacciones: 43,
	},
	{
		titulo: 'Optimización de imágenes para la web: Consejos y herramientas útiles',
		descripcion:
			'Descubre cómo optimizar tus imágenes para la web sin sacrificar calidad, utilizando herramientas y técnicas eficientes para reducir el tamaño de los archivos.',
		categoria: 'Desarrollo Web',
		autor: 'Mario López',
		tags: ['optimización de imágenes', 'rendimiento', 'desarrollo web'],
		tiempoLectura: '6 minutos',
		fechaCreacion: '2024-03-15',
		imagen: 'https://picsum.photos/id/45/200/300',
		numReacciones: 31,
	},
	{
		titulo: 'Implementación de autenticación basada en tokens JWT en tu API REST',
		descripcion:
			'Aprende a implementar autenticación basada en tokens JWT (JSON Web Tokens) en tu API REST para proteger rutas y recursos de forma segura y eficiente.',
		categoria: 'Seguridad',
		autor: 'Javier García',
		tags: ['JWT', 'autenticación', 'seguridad web'],
		tiempoLectura: '9 minutos',
		fechaCreacion: '2024-03-12',
		imagen: 'https://picsum.photos/id/46/200/300',
		numReacciones: 52,
	},
	{
		titulo: 'Cómo realizar pruebas unitarias con Jest: Guía paso a paso',
		descripcion:
			'Aprende a escribir y ejecutar pruebas unitarias eficientes para tus aplicaciones JavaScript utilizando Jest, un framework de pruebas desarrollado por Facebook.',
		categoria: 'Testing',
		autor: 'Carmen Martínez',
		tags: ['Jest', 'pruebas unitarias', 'testing'],
		tiempoLectura: '11 minutos',
		fechaCreacion: '2024-03-10',
		imagen: 'https://picsum.photos/id/47/200/300',
		numReacciones: 47,
	},
	{
		titulo: '10 Librerías JavaScript populares que debes conocer en 2024',
		descripcion:
			'Descubre algunas de las librerías JavaScript más populares y útiles que deberías conocer y considerar utilizar en tus proyectos de desarrollo web este año.',
		categoria: 'JavaScript',
		autor: 'Marcos Sánchez',
		tags: ['JavaScript', 'librerías', 'desarrollo web'],
		tiempoLectura: '7 minutos',
		fechaCreacion: '2024-03-08',
		imagen: 'https://picsum.photos/id/48/200/300',
		numReacciones: 39,
	},
	{
		titulo: 'Introducción a la programación reactiva con RxJS: Conceptos básicos y ejemplos prácticos',
		descripcion:
			'Aprende los conceptos básicos de la programación reactiva y cómo aplicarlos en tus proyectos JavaScript utilizando RxJS, una librería de programación reactiva.',
		categoria: 'Reactividad',
		autor: 'Eduardo Fernández',
		tags: ['RxJS', 'programación reactiva', 'JavaScript'],
		tiempoLectura: '10 minutos',
		fechaCreacion: '2024-03-05',
		imagen: 'https://picsum.photos/id/49/200/300',
		numReacciones: 56,
	},
	{
		titulo: 'Cómo crear y consumir APIs RESTful con Node.js y Express',
		descripcion:
			'Aprende a crear APIs RESTful robustas con Node.js y Express, utilizando buenas prácticas y patrones de diseño para desarrollar servicios web escalables y mantenibles.',
		categoria: 'Node.js',
		autor: 'Roberto Gómez',
		tags: ['Node.js', 'Express', 'APIs'],
		tiempoLectura: '12 minutos',
		fechaCreacion: '2024-03-02',
		imagen: 'https://picsum.photos/id/50/200/300',
		numReacciones: 65,
	},
	{
		titulo: 'Principios básicos de diseño UI/UX para desarrolladores web',
		descripcion:
			'Conoce los principios básicos de diseño de interfaz de usuario (UI) y experiencia de usuario (UX) que todo desarrollador web debería entender para crear mejores productos.',
		categoria: 'Diseño',
		autor: 'Sofía Pérez',
		tags: ['UI', 'UX', 'diseño web'],
		tiempoLectura: '8 minutos',
		fechaCreacion: '2024-02-28',
		imagen: 'https://picsum.photos/id/51/200/300',
		numReacciones: 48,
	},
];

export { posts };
